# Generated by Django 3.0 on 2019-12-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.CharField(max_length=60)),
                ('uploader', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('length', models.IntegerField()),
                ('views', models.IntegerField()),
                ('rate', models.FloatField()),
                ('ratings', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        )
    ]
