# Generated by Django 3.0 on 2019-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('videoID', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageRank',
            fields=[
                ('videoID', models.CharField(max_length=60, unique=True)),
                ('pagerank', models.FloatField()),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('videoID', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('inRank', models.IntegerField()),
                ('outRank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatedIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('videoID', models.CharField(max_length=60)),
                ('relatedID', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateVideo',
            fields=[
                ('videoID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('views', models.IntegerField()),
                ('rate', models.FloatField()),
                ('ratings', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('uploads', models.IntegerField()),
                ('watches', models.IntegerField()),
                ('friends', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoRate',
            fields=[
                ('videoID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('vbr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoSize',
            fields=[
                ('videoID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoSizeRate',
            fields=[
                ('videoID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('vbr', models.FloatField()),
            ],
        ),
    ]
